import type { Metadata } from 'next'
import { Urbanist } from 'next/font/google'
import './globals.css'
import SideBar from '@/components/SideBar'
import SideBarItem from '@/components/SideBarItem'
import Icon from '@/components/Icon'
import Badge from '@/components/Badge'

const urbanistFont = Urbanist({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Content Management',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={urbanistFont.className}>
        <SideBar
          navItems={<>
            <SideBarItem icon={<Icon icon="dashboard"/>} label="Dashboard"/>
            <SideBarItem icon={<Icon icon="content"/>} label="Content" active/>
            <SideBarItem icon={<Icon icon="team"/>} label="Team"/>
            <SideBarItem icon={<Icon icon="computer"/>} label="App/Web"/>
            <SideBarItem icon={<Icon icon="analytics"/>} label="Analytics" badge={<Badge label="3"/>}/>
            <SideBarItem icon={<Icon icon="media"/>} label="Media" badge={<Badge label="16"/>}/>
            <SideBarItem icon={<Icon icon="notification"/>} label="Notification"/>
            <SideBarItem icon={<Icon icon="settings"/>} label="Settings"/>
            </>}
          footerItems={<>
            <SideBarItem key={1} icon={<Icon icon="headphone"/>} label="Contact Support"/>
            </>}
        >
          {children}
        </SideBar>
      </body>
    </html>
  )
}
